version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: "0000"
    volumes:
        - ./db/mysql/data:/var/lib/mysql
        - ./db/mysql/config:/etc/mysql/conf.d
        - ./db/mysql/init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - 6379:6379

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - 9090:8080