server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    include: security
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/auth/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: newsfeed-service
          uri: lb://NEWSFEED-SERVICE
          predicates:
            - Path=/api/newsfeed/**
          filters:
            - AuthorizationHeaderFilter
        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activity/**
            - Method=Get, POST
          filters:
            - AuthorizationHeaderFilter
