spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql_db?serverTimezone=Asia/Seoul
    username: root
    password: "0000"
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  batch:
    job:
      name: csvFileItemReaderJob
    jdbc:
      initialize-schema: always